param(
  [string]$TargetPath = ".\food-truck-booking"
)

$ErrorActionPreference = "Stop"

$dirs = @(
  "src/app",
  "src/app/api",
  "src/app/api/public",
  "src/app/api/public/locations",
  "src/app/login",
  "src/app/signup",
  "src/app/public-map",
  "src/app/admin",
  "src/app/admin/businesses",
  "src/app/admin/trucks",
  "src/app/business/dashboard",
  "src/app/business/requests/new",
  "src/app/truck/dashboard",
  "src/components",
  "src/lib",
  "src/lib/supabase",
  "src/types",
  "supabase/migrations",
  "scripts"
)

foreach ($dir in $dirs) {
  New-Item -ItemType Directory -Force -Path (Join-Path $TargetPath $dir) | Out-Null
}

function Write-TextFile {
  param([string]$RelativePath, [string]$Content)
  $full = Join-Path $TargetPath $RelativePath
  $folder = Split-Path $full -Parent
  if (-not (Test-Path $folder)) {
    New-Item -ItemType Directory -Force -Path $folder | Out-Null
  }
  Set-Content -Path $full -Value $Content -Encoding UTF8
}

Write-TextFile "package.json" @'
{
  "name": "food-truck-booking",
  "version": "0.2.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint",
    "typecheck": "tsc --noEmit"
  },
  "dependencies": {
    "next": "15.2.4",
    "react": "19.0.0",
    "react-dom": "19.0.0",
    "@supabase/ssr": "^0.5.2",
    "@supabase/supabase-js": "^2.49.1",
    "react-leaflet": "^5.0.0",
    "leaflet": "^1.9.4",
    "nodemailer": "^6.10.0"
  },
  "devDependencies": {
    "typescript": "^5.8.2",
    "@types/node": "^22.13.10",
    "@types/react": "^19.0.10",
    "@types/react-dom": "^19.0.4",
    "@types/leaflet": "^1.9.18",
    "@types/nodemailer": "^6.4.17"
  }
}
'@

Write-TextFile ".env.example" @'
NEXT_PUBLIC_SUPABASE_URL=
NEXT_PUBLIC_SUPABASE_ANON_KEY=
SUPABASE_SERVICE_ROLE_KEY=
NEXT_PUBLIC_APP_URL=http://localhost:3000
SMTP_HOST=
SMTP_PORT=587
SMTP_SECURE=false
SMTP_USER=
SMTP_PASS=
SMTP_FROM=notifications@example.com
'@

Write-TextFile "README.md" @'
Food Truck Booking scaffold generated by PowerShell.
This version includes placeholders for:
- Vercel + Supabase deployment
- SMTP email notifications
- truck conflict checking
- admin audit trail and rollback controls
Run npm install, load the SQL migration, then deploy to Vercel.
'@

Write-TextFile "supabase/migrations/001_init.sql" @'
-- Replace this placeholder with the packaged migration from the full scaffold.
-- It should include tables for profiles, truck_requests, truck_notifications,
-- truck_locations, feature_flags, change_control_versions, and admin_audit_log.
'@

$placeholderFiles = @(
  "src/app/layout.tsx",
  "src/app/page.tsx",
  "src/app/login/page.tsx",
  "src/app/signup/page.tsx",
  "src/app/public-map/page.tsx",
  "src/app/admin/page.tsx",
  "src/app/admin/businesses/page.tsx",
  "src/app/admin/trucks/page.tsx",
  "src/app/business/dashboard/page.tsx",
  "src/app/business/requests/new/page.tsx",
  "src/app/truck/dashboard/page.tsx",
  "src/app/api/public/locations/route.ts",
  "src/components/Shell.tsx",
  "src/components/PublicMap.tsx",
  "src/components/PublicMapInner.tsx",
  "src/lib/actions.ts",
  "src/lib/auth.ts",
  "src/lib/env.ts",
  "src/lib/email.ts",
  "src/lib/supabase/browser.ts",
  "src/lib/supabase/server.ts",
  "src/lib/supabase/admin.ts",
  "src/types/db.ts",
  "middleware.ts",
  "next.config.mjs",
  "tsconfig.json",
  "next-env.d.ts"
)

foreach ($file in $placeholderFiles) {
  if (-not (Test-Path (Join-Path $TargetPath $file))) {
    Write-TextFile $file "// Replace with packaged scaffold content.`n"
  }
}

Write-Host "Food Truck Booking scaffold created at $TargetPath"
